- name: Playbook to run green thread collection tests
  hosts: localhost
  connection: local
  vars:
    gateway_hostname: localhost:8000
    gateway_username: admin
    gateway_password: admin
    gateway_validate_certs: false
    gateway_configuration_users_secure_logging: false
  collections:
    - ansible.platform
  tasks:
    - name: Add settings
      ansible.platform.settings:
        settings:
          gateway_access_token_expiration: 700
        gateway_hostname: "{{ gateway_hostname }}"
        gateway_username: "{{ gateway_username }}"
        gateway_password: "{{ gateway_password }}"
        gateway_validate_certs: false
        
#  tasks:
    # - name: Include ad-hoc role
    #   include_role:
    #     name: ad_hoc_command
      # collections:
      #   - ansible.controller
